# Generated by Django 4.1.1 on 2022-11-05 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('is_manager', models.BooleanField(default=False, verbose_name='manager status')),
                ('is_player', models.BooleanField(default=False, verbose_name='player status')),
                ('is_referee', models.BooleanField(default=False, verbose_name='referee status')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('campus_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.campus')),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('position', models.CharField(blank=True, choices=[('POR', 'Portero'), ('DEF', 'Defensa'), ('MED', 'Medio'), ('DEL', 'Delantero')], max_length=3)),
                ('sanction_status', models.CharField(choices=[('D', 'Disponible'), ('S', 'Suspendido')], default='D', max_length=1)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('matches_played', models.IntegerField(default=0)),
                ('goals_for', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('league_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.leagues')),
                ('manager', models.ForeignKey(limit_choices_to={'is_manager': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayerRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField(auto_now_add=True)),
                ('goals', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0, unique=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.players')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_team1', models.IntegerField(default=0)),
                ('goals_team2', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.field')),
                ('referee_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.referees')),
                ('team_name1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team1', to='api.teams')),
                ('team_name2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team2', to='api.teams')),
            ],
        ),
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
