# Generated by Django 4.1.1 on 2022-11-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayerrecords',
            name='player',
            field=models.ForeignKey(limit_choices_to={'is_player': True}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leagues'),
        ),
    ]
