# Generated by Django 4.1.1 on 2022-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='matches_played',
            field=models.IntegerField(default=0),
        ),
    ]
