# Generated by Django 4.1.1 on 2022-11-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_teams_matches_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='manager status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_player',
            field=models.BooleanField(default=False, verbose_name='player status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_referee',
            field=models.BooleanField(default=False, verbose_name='referee status'),
        ),
    ]
