# Generated by Django 4.1.1 on 2022-11-11 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_teams_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='manager',
            new_name='manager_name',
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leagues'),
        ),
    ]
